### ISSUE TITLE
Update of mac-ages.csv

### ISSUE THREAD

**Issue by robharmsen** [HelgeKeck/winfi#2]
Hi,
there is an updated file of "mac-ages.csv" available at another GitHub repository. When i mannually replace the files in the application directory, WinFi is not seeing the updates file en keeps the version info on the default 01/01/2021. How to update the mac ages database?

Great tool by the way!
Regards,
Rob

**Comment by HelgeKeck** [comment]
place it here:

`C:\Users\USERNAME\AppData\Local\WinFi`

will have a look if we cna make the database url configureable
