### ISSUE TITLE
Pro license for engineering

### ISSUE THREAD

**Issue by robharmsen** [HelgeKeck/winfi#3]
Hi,
how to obtain a Pro license for WinFi so I can activate all other options? What is the price and where can I buy a license?
Regards,

Rob

**Comment by OrrFi** [comment]
Great work. Same question.

**Comment by HelgeKeck** [comment]
please ask in the discord server about licensing, there is a link in the info page in winfi

**Comment by OrrFi** [comment]
Sdiscord server.. where is this? link bitte.

**Comment by robharmsen** [comment]
Hi HelgeKeck,
there is no Discord link available under Info in WinFi see the attached screenshot
![Schermafbeelding 2024-09-13 091704](https://github.com/user-attachments/assets/fe4370eb-4efc-4b01-9c40-d4a51af103be)

Can you share it with me please? Other Discord links are unavailable or expired. Appreciate your help!
Regards,
Rob

**Comment by HelgeKeck** [comment]
update the Application
